"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase"; 

export default function AdminUserManagement() {
  const [isMounted, setIsMounted] = useState(false);
  const [isListLoading, setIsListLoading] = useState(true);
  const [students, setStudents] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  
  // Modal State Parameters
  const [selectedStudent, setSelectedStudent] = useState(null);
  const [isModalLoading, setIsModalLoading] = useState(false);
  const [studentHistory, setStudentHistory] = useState([]);

  useEffect(() => {
    setIsMounted(true);

    // ==========================================
    // 🟢 FETCH ALL ENROLLED PROFILES FROM SUPABASE
    // ==========================================
    const fetchEnrolledStudentsList = async () => {
      try {
        setIsListLoading(true);
        // Query rows directly out of your active profiles schema
        const { data, error } = await supabase
          .from("profiles")
          .select("id, full_name, email, phone_number, created_at")
          .order("created_at", { ascending: false });

        if (error) throw error;
        setStudents(data || []);
      } catch (err) {
        console.error("Failed gathering system profile dimensions:", err);
      } finally {
        setIsListLoading(false);
      }
    };

    fetchEnrolledStudentsList();
  }, []);

  // ==========================================
  // 🟢 FETCH DRILL-DOWN INFO FOR TARGET STUDENT
  // ==========================================
  const handleOpenStudentProfileModal = async (student) => {
    setSelectedStudent(student);
    setIsModalLoading(true);
    setStudentHistory([]);
    
    try {
      // Query every mock exam attempt generated by this student's account
      const { data: attempts, error } = await supabase
        .from("attempt_sessions")
        .select("test_id, status, current_score, total_answered, created_at")
        .eq("user_id", student.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      setStudentHistory(attempts || []);
    } catch (err) {
      console.error("Failed fetching itemized target session metrics:", err);
    } finally {
      setIsModalLoading(false);
    }
  };

  // Filter list matching search parameter criteria
  const filteredStudents = students.filter(s => 
    (s.full_name?.toLowerCase() || "").includes(searchTerm.toLowerCase()) ||
    (s.email?.toLowerCase() || "").includes(searchTerm.toLowerCase()) ||
    (s.phone_number || "").includes(searchTerm)
  );

  if (!isMounted) return null;

  return (
    <div style={{ animation: "fadeInUsersPanel 0.4s ease-out forwards" }}>
      
      {/* HEADER SECTION */}
      <div className="admin-header-row" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "24px" }}>
        <div>
          <h1 style={{ fontSize: "24px", fontWeight: "800", margin: "0 0 4px 0", letterSpacing: "-0.4px" }}>User Management</h1>
          <p style={{ fontSize: "13px", color: "var(--admin-text-muted)", margin: "0" }}>Audit registered student profiles, diagnostic permissions, and test execution histories.</p>
        </div>

        {/* Dynamic Pure CSS Search Input Component */}
        <div style={{ position: "relative", display: "flex", alignItems: "center" }}>
          <span className="material-icons" style={{ position: "absolute", left: "12px", color: "var(--admin-text-muted)", fontSize: "18px" }}>search</span>
          <input 
            type="text" 
            placeholder="Search by name, email, phone..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            style={{
              padding: "10px 16px 10px 38px",
              fontSize: "13px",
              width: "280px",
              backgroundColor: "var(--admin-surface)",
              border: "1px solid var(--admin-border)",
              borderRadius: "8px",
              color: "var(--admin-text-main)",
              outline: "none"
            }}
          />
        </div>
      </div>

      {/* 🟢 USERS LISTING DATA MATRIX */}
      <div className="admin-metric-card" style={{ padding: "0", overflow: "hidden" }}>
        {isListLoading ? (
          <div style={{ padding: "40px", textAlign: "center", color: "var(--admin-text-muted)" }}>
            <div className="admin-spinner" style={{ margin: "0 auto 12px" }}></div>
            <span>Synchronizing user matrix arrays...</span>
          </div>
        ) : filteredStudents.length === 0 ? (
          <div style={{ padding: "40px", textAlign: "center", color: "var(--admin-text-muted)", fontSize: "13px" }}>
            No matching student records found in the cluster.
          </div>
        ) : (
          <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "left", fontSize: "13px" }}>
              <thead>
                <tr style={{ borderBottom: "1px solid var(--admin-border)", backgroundColor: "rgba(100,116,139,0.02)" }}>
                  <th style={{ padding: "14px 20px", color: "var(--admin-text-muted)", fontWeight: "700" }}>Student</th>
                  <th style={{ padding: "14px 20px", color: "var(--admin-text-muted)", fontWeight: "700" }}>Email Address</th>
                  <th style={{ padding: "14px 20px", color: "var(--admin-text-muted)", fontWeight: "700" }}>Phone Number</th>
                  <th style={{ padding: "14px 20px", color: "var(--admin-text-muted)", fontWeight: "700" }}>Joined Date</th>
                </tr>
              </thead>
              <tbody>
                {filteredStudents.map((student) => (
                  <tr 
                    key={student.id} 
                    onClick={() => handleOpenStudentProfileModal(student)}
                    className="admin-table-row-interactive"
                    style={{ 
                      borderBottom: "1px solid var(--admin-border)", 
                      cursor: "pointer"
                    }}
                  >
                    <td style={{ padding: "14px 20px", display: "flex", alignItems: "center", gap: "12px" }}>
                      <div style={{ 
                        width: "32px", height: "32px", borderRadius: "50%", 
                        background: "var(--admin-primary-light)", color: "var(--admin-primary)",
                        display: "flex", alignItems: "center", justifyCenter: "center", justifyContent: "center",
                        fontSize: "12px", fontWeight: "700"
                      }}>
                        {student.full_name ? student.full_name.charAt(0).toUpperCase() : "S"}
                      </div>
                      <span style={{ fontWeight: "600" }}>{student.full_name || "Unnammed Student"}</span>
                    </td>
                    <td style={{ padding: "14px 20px", color: "var(--admin-text-muted)" }}>{student.email}</td>
                    <td style={{ padding: "14px 20px", color: "var(--admin-text-muted)" }}>{student.phone_number || "—"}</td>
                    <td style={{ padding: "14px 20px", color: "var(--admin-text-muted)" }}>
                      {new Date(student.created_at).toLocaleDateString("en-IN", { day: 'numeric', month: 'short', year: 'numeric' })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ======================================================== 
        🟢 80% SCREEN EXPANSION PROFILE OVERLAY MODAL (BLURRED BACKGROUND)
        ======================================================== */}
      {selectedStudent && (
        <div style={{
          position: "fixed",
          inset: 0,
          backgroundColor: "rgba(2, 6, 23, 0.4)",
          backdropFilter: "blur(8px)",
          WebkitBackdropFilter: "blur(8px)",
          zIndex: 99999,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          animation: "fadeInModalOverlay 0.2s ease-out"
        }}>
          
          <div style={{
            width: "80%",
            height: "80%",
            backgroundColor: "var(--admin-surface)",
            border: "1px solid var(--admin-border)",
            borderRadius: "16px",
            boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.4)",
            display: "flex",
            flexDirection: "column",
            overflow: "hidden",
            animation: "scaleUpModalViewport 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)"
          }}>
            
            {/* Modal Top Control Header Bar */}
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 24px", borderBottom: "1px solid var(--admin-border)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "14px" }}>
                <span className="material-icons" style={{ color: "var(--admin-primary)", fontSize: "24px" }}>account_circle</span>
                <h2 style={{ fontSize: "18px", fontWeight: "800", margin: 0 }}>Detailed Academic Dossier</h2>
              </div>
              <button 
                onClick={() => setSelectedStudent(null)}
                style={{ background: "transparent", border: "none", cursor: "pointer", color: "var(--admin-text-muted)", display: "flex" }}
              >
                <span className="material-icons">close</span>
              </button>
            </div>

            {/* Modal Split View Workspace Content */}
            <div style={{ flex: 1, display: "flex", overflow: "hidden" }}>
              
              {/* Left Profile Segment Info Side */}
              <div style={{ width: "30%", borderRight: "1px solid var(--admin-border)", padding: "24px", boxSizing: "border-box", display: "flex", flexDirection: "column", gap: "20px", backgroundColor: "rgba(100,116,139,0.01)" }}>
                <div style={{ textAlign: "center", paddingBottom: "20px", borderBottom: "1px solid var(--admin-border)" }}>
                  <div style={{ width: "64px", height: "64px", borderRadius: "50%", background: "var(--admin-primary-light)", color: "var(--admin-primary)", fontSize: "24px", fontWeight: "700", display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 12px" }}>
                    {selectedStudent.full_name ? selectedStudent.full_name.charAt(0).toUpperCase() : "S"}
                  </div>
                  <h3 style={{ fontSize: "16px", fontWeight: "700", margin: "0 0 4px 0" }}>{selectedStudent.full_name}</h3>
                  <span style={{ fontSize: "11px", color: "var(--admin-text-muted)", fontWeight: "600", textTransform: "uppercase" }}>Student ID Node</span>
                </div>

                <div style={{ display: "flex", flexDirection: "column", gap: "12px", fontSize: "13px" }}>
                  <div>
                    <label style={{ display: "block", fontSize: "10px", fontWeight: "700", textTransform: "uppercase", color: "var(--admin-text-muted)", marginBottom: "4px" }}>Email Index</label>
                    <span style={{ fontWeight: "500", wordBreak: "break-all" }}>{selectedStudent.email}</span>
                  </div>
                  <div>
                    <label style={{ display: "block", fontSize: "10px", fontWeight: "700", textTransform: "uppercase", color: "var(--admin-text-muted)", marginBottom: "4px" }}>Contact Number</label>
                    <span style={{ fontWeight: "500" }}>{selectedStudent.phone_number || "No Phone Registered"}</span>
                  </div>
                  <div>
                    <label style={{ display: "block", fontSize: "10px", fontWeight: "700", textTransform: "uppercase", color: "var(--admin-text-muted)", marginBottom: "4px" }}>Global Identification Token</label>
                    <span style={{ fontFamily: "monospace", fontSize: "11px", color: "var(--admin-text-muted)" }}>{selectedStudent.id}</span>
                  </div>
                </div>
              </div>

              {/* Right Profile Segment Historical Metrics Side */}
              <div style={{ flex: 1, padding: "24px", boxSizing: "border-box", overflowY: "auto" }}>
                <h3 style={{ fontSize: "14px", fontWeight: "700", marginBottom: "16px" }}>Mock Test Attempt Index History</h3>

                {isModalLoading ? (
                  <div style={{ textAlign: "center", padding: "40px", color: "var(--admin-text-muted)" }}>
                    <div className="admin-spinner" style={{ margin: "0 auto 12px" }}></div>
                    <span>Extracting session performance matrix...</span>
                  </div>
                ) : studentHistory.length === 0 ? (
                  <div style={{ border: "1px dashed var(--admin-border)", borderRadius: "8px", padding: "32px", textAlign: "center", color: "var(--admin-text-muted)", fontSize: "13px" }}>
                    This user hasn't initialized any mock portal exam tokens yet.
                  </div>
                ) : (
                  <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                    {studentHistory.map((session, i) => (
                      <div 
                        key={i} 
                        style={{
                          border: "1px solid var(--admin-border)",
                          borderRadius: "8px",
                          padding: "16px",
                          display: "flex",
                          justifyContent: "space-between",
                          alignItems: "center",
                          backgroundColor: "var(--admin-surface)"
                        }}
                      >
                        <div>
                          <div style={{ fontWeight: "700", fontSize: "13px", marginBottom: "4px" }}>{session.test_id}</div>
                          <div style={{ fontSize: "11px", color: "var(--admin-text-muted)" }}>
                            Attempted on {new Date(session.created_at).toLocaleDateString("en-IN", { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}
                          </div>
                        </div>

                        <div style={{ display: "flex", alignItems: "center", gap: "24px", textAlign: "right" }}>
                          <div>
                            <div style={{ fontSize: "10px", textTransform: "uppercase", fontWeight: "700", color: "var(--admin-text-muted)", marginBottom: "2px" }}>Status</div>
                            <span style={{ 
                              fontSize: "11px", 
                              fontWeight: "700", 
                              padding: "2px 8px", 
                              borderRadius: "4px",
                              backgroundColor: session.status === "completed" ? "rgba(16, 185, 129, 0.15)" : "rgba(245, 158, 11, 0.15)",
                              color: session.status === "completed" ? "#10b981" : "#f59e0b"
                            }}>
                              {session.status}
                            </span>
                          </div>

                          <div>
                            <div style={{ fontSize: "10px", textTransform: "uppercase", fontWeight: "700", color: "var(--admin-text-muted)", marginBottom: "2px" }}>Score Output</div>
                            <span style={{ fontWeight: "800", fontSize: "14px", color: "var(--admin-primary)" }}>{session.current_score ?? "—"}</span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

            </div>
          </div>
        </div>
      )}

      {/* Embedded CSS Animations & Table Hover Rules */}
      <style>{`
        .admin-table-row-interactive:hover {
          background-color: rgba(100, 116, 139, 0.04) !important;
        }
        .admin-spinner {
          width: 24px; height: 24px;
          border: 3px solid var(--admin-primary);
          border-top-color: transparent;
          border-radius: 50%;
          animation: spinNode 0.8s linear infinite;
        }
        @keyframes spinNode { to { transform: rotate(360deg); } }
        @keyframes fadeInUsersPanel { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes fadeInModalOverlay { from { opacity: 0; } to { opacity: 1; } }
        @keyframes scaleUpModalViewport { from { opacity: 0; transform: scale(0.96); } to { opacity: 1; transform: scale(1); } }
      `}</style>

    </div>
  );
}